#Api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-app-api
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier-app-api
  template:
    metadata:
      labels:
        app: three-tier-app-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        #Comment if trying locally
        "type": user-node
      containers:
        - name: three-tier-app-api
          image: ghcr.io/macel94/aks-three-tier-app/api:master
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: REDIS_CONNECTIONSTRING
              value: "redis-db-sv"
---
apiVersion: v1
kind: Service
metadata:
  name: three-tier-app-api-sv
  namespace: {{ .Values.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: three-tier-app-api
---
#Autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: three-tier-app-api-hpa
  namespace: {{ .Values.Namespace }}
spec:
  maxReplicas: 30 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: three-tier-app-api
  targetCPUUtilizationPercentage: 50 # target CPU utilization
